### ISSUE TITLE
Geotiff replacement - 1748 map

### ISSUE THREAD

**Issue by gshap** [YaleDHLab/gathering-a-building#112]
Hi Doug, 
At your convenience, here is the link for the corrected Geotiff for the first map (1748) in GAB / Historical Geography section

https://www.dropbox.com/s/ovak6qk18y5re5t/1748_Wadsworth-Plan_New-Haven_1806-Beinecke_v3.tif?dl=0

Please let me know at your convenience if for some reason the file is bad or doesn't look right. 
Thanks
Gideon

**Comment by gshap** [comment]
Good morning Doug, not sure if you had a chance to look at this yet... of course doesn't need to be resolved today, but do let me know if there's an issue with the updated Geotiff. thanks!
G

**Comment by duhaime** [comment]
Hey @gshap, haven't had a chance yet but I'll jump on this now and will ping you once the changes are live...

**Comment by duhaime** [comment]
This should be all set @gshap! If you have a second, could I please ask you to take a look to make sure the new map looks fine? (You may need to clear your cache to see the changes)

I also updated the marker icon positions on the landing route--I don't know the content very well, so I hope those look alright as well! :)

**Comment by gshap** [comment]
I cleared the cache and opened the local server... looks like it's still 90 degrees off. Strange. We'll have to look into it. 
Thank you for updating the marker icon positions - looks fine for now.

**Comment by duhaime** [comment]
It looks like your updated map image was indeed rotated (the old map is on the left, the new one is on the right), though it appears to have been rotated 270 degrees: 

<img width="349" alt="screen shot 2017-10-10 at 12 48 34 pm" src="https://user-images.githubusercontent.com/4801116/31399170-609f3d90-adb9-11e7-910e-caa24746e10b.png">

Let's catch up later today to investigate...

**Comment by gshap** [comment]
Ah good, the new one looks correct

**Comment by duhaime** [comment]
Excellent, I'll close this one out!
