### ISSUE TITLE
Try to obtain digital building model

### ISSUE THREAD

**Issue by gshap** [YaleDHLab/gathering-a-building#13]
Just informed the model is in Autodesk Revit (a CAD program), and we are trying to schedule a video conference to do a walk through.

**Comment by duhaime** [comment]
It looks like there are [a few options](http://stackoverflow.com/questions/30796342/convert-autodesk-dwg-and-dwf-files-to-three-js-json-format) for getting the CAD data ready for something like [WebGL via three.js](http://threejs.org/). I'm really looking forward to checking out those files!

**Comment by gshap** [comment]
Aha!
