### ISSUE TITLE
Generate georectified images for production

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/gathering-a-building#23]
The functionality to display the map overlays is ready, so we can go ahead and process these images. Once they're done, we can run a simple `gdal2tiles.py -z 16-20 {{georectified tif file.tif}}` command to get the smaller tiles once the geotiffs are ready.

**Comment by gshap** [comment]
Sounds good, Doug. So that means I should feed in all the geotiffs for processing?

**Comment by duhaime** [comment]
Yes sir! If you can upload the georeferenced geotifs to a folder in the dropbox, I'll put them through the gdal2tile grinder, upload them to S3, and update the urls in the app to fetch the latest...

**Comment by duhaime** [comment]
We now have geotiffs for: 1748, 1802, 1824, 1849, 1874, 1893, and 1973. 

The json that maps years to building ids also has the following years: 1911, 1940, 2000. 

We should procure georectified tiffs for these years so we can split them into tiles and load into S3.
