### ISSUE TITLE
Identify / generate landing page image asset

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/gathering-a-building#5]
The current landing page hosts a profile image of the Yale Museum of British Art, and needs replacing with the proper image asset.

**Comment by gshap** [comment]
The desired asset is derived from a CAD model (not sure what format) built in Autodesk Revit. Attempting to coordinate a video conference with the architect to walk us through it.

**Comment by duhaime** [comment]
Amen! I started looking into [Autodesk's developer documentation](https://developer.autodesk.com/en/docs/viewer/v2/overview/) and am doing background research on WebGL too, in the case that we can acquire that model. Fingers crossed!

**Comment by duhaime** [comment]
This is all set
