### ISSUE TITLE
Design QA 1.2

### ISSUE THREAD

**Issue by ghost** [YaleDHLab/gathering-a-building#73]
- [x] When one clicks on the material points in the Carto map, the images do not appear as they are hosted at the gatheringabuilding.yale.edu domain, which is password protected.
- [x] "Show Map" button - move 5 px down so that it is vertically centered to button
- [x] New image available for the "Go Back" button image
- [x] Landing page overlays: Can we add a 50% drop-shadow to the overlays to differentiate it from the landing page graphic?  
- [x] Page heading color: #3399CC (which is just to the left of "Next" in the text template)
- [x] Position the menu icon halfway between the screen edge and the white box around the site header. 
- [x] DHLab logo right margin should be same as the left margin of nav icon.

**Comment by duhaime** [comment]
Just to check, for the "Go Back" button, should we use yale_colleges_sm.png? That looks like the one you were setting up, I just wanted to check!

On the brand logo, I cut down the right margin because it's much wider than the navigation button--does the result look alright?
