### ISSUE TITLE
UX QA 1.3

### ISSUE THREAD

**Issue by ghost** [YaleDHLab/gathering-a-building#81]
- [x] Let's transition the site such that no password will be required to view the site or access images from the media library/
- [x] Can it be set up so that's it's possible to update and preview changes in the browser? While it runs quickly using the localhost, it's not easy to get things up and running without advanced development knowledge. 
- [x] Landing page overlays: Let's see if it's possible to place the overlays over the buttons I would create an exception only when the overlay is within 25 pixels of the screen edge. In most cases, because we have ample negative space over the image for most desktop experiences, this should be ok. 
- [x] Overlay size. The thumbnail can be sized to 180 x 180 px and the full panel is now 480 px wide x 180 px tall. 
- [x] Overlay behavior: Once it's open, allow OnClick to close it. 
- [x] Historical Geographies: The slider for the maps needs to reflect the new selection of maps:
- 1748 Wadsworth Plan
- 1824 Doolittle Plan 
- 1849 Buckingham Map 
- 1874 Lyman/Butler Map
- 1893 Hill Map
- 1911 Atlas of New Haven
- 1937 Home Owners Loan Corporation Map
- 1973 Sanborn Fire Insurance Map
- 2000 Cooper Robertson Plan
- [x] Historical Geographies: The section will begin w/ some intro text so it won't need to start changing map views until 1824.
- [x] Menu: Instead of Downloads and Links, maybe for now we just hide the pages while there is no content? 
- [x] Adding pages: Let's configure a simple way to add pages links to the menu
- [x] Overlay admin: how will the overlay Links be connected to articles? 
- [x] Regarding additional content, there is an Articles folder in the Dropbox which includes comps of the connecting articles and their related images. This is subject to change per Gideon's curatorial suggestions.

**Comment by duhaime** [comment]
This is all set via #82, with the exception of the dev setup discussed in item number 2 above, and the last of the maps identified above (2000 Cooper Robertson), which we don't have in hand just yet. Once that map is in, I'll load it up...

**Comment by duhaime** [comment]
Closed via #82
