### ISSUE TITLE
HIST. GEOGR. – Replacing 1910 with 1911

### ISSUE THREAD

**Issue by gshap** [YaleDHLab/gathering-a-building#86]
Apologies, the 1911 map bucket has the wrong file attached (1910). The correct 1911 Geotiff can be found here:
https://www.dropbox.com/s/6yxbull6izq30ye/1911NH.zip?dl=0

In other words, we are not adding a date tab, just replacing the attached map tiles.

**Comment by duhaime** [comment]
This is on hold until we lay hands on the 1911 map from Miriam...
